title: "Danni Yagici Nielsen - Rejser & mad"
description: "Bloggen af Danni Yagici Nielsen, handler om smukke steder og l√¶kker mad!"
theme: minima

timezone: Europe/Copenhagen
permalink: /blog/:year/:month/:day/:title/

# Optional: makes excerpts nicer if you use <!--more-->
excerpt_separator: "<!--more-->"
