title:              Danni Yagici Nielsen - Rejs & Spis Godt
email:
description:        Danni Yagici Nielsen deler rejseguider, madoplevelser og lokale anbefalinger fra Middelhavet.
author:             Danni Yagici Nielsen
baseurl:            ""
url:                "https://www.danniyagicinielsen.dk"

# Social Profiles
twitter_username:
github_username:
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/blog/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
